### ISSUE TITLE
ArgumentNullException: Value cannot be null

### ISSUE THREAD

**Issue by ChrisTorng** [madskristensen/WebAnalyzer#1]
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at Newtonsoft.Json.Linq.Extensions.Value[T,U](IEnumerable'1 value)
   at WebLinter.EsLinter.ParseErrors(String output)
   at WebLinter.LinterBase.Lint(FileInfo[] files)
   at WebLinter.LinterBase.Run(String[] files)
   at WebLinter.LinterFactory.Lint(ISettings settings, String[] fileNames)
   at WebLinterVsix.LinterService.<>c__DisplayClass4_0.<Lint>b__0(Object o) in C:\projects\weblinter\src\WebLinterVsix\LinterService.cs:line 76

**Comment by ChrisTorng** [comment]
Another error happen then:
System.NullReferenceException: Object reference not set to an instance of an object.
   at WebLinter.CssLinter.ParseErrors(String output)
   at WebLinter.LinterBase.Lint(FileInfo[] files)
   at WebLinter.LinterBase.Run(String[] files)
   at WebLinter.LinterFactory.Lint(ISettings settings, String[] fileNames)
   at WebLinterVsix.LinterService.<>c__DisplayClass4_0.<Lint>b__0(Object o) in C:\projects\weblinter\src\WebLinterVsix\LinterService.cs:line 76

**Comment by madskristensen** [comment]
Can you try to delete the node module cache located at **%localappdata%\temp\WebLinter\1.x.x** and see if that fixes it? I'm adding better error handling now as well

**Comment by madskristensen** [comment]
Fixed in latest CI build which can be installed from here http://vsixgallery.com/extension/36bf2130-106e-40f2-89ff-a2bdac6be879/

**Comment by ChrisTorng** [comment]
I deleted %localappdata%\temp\WebLinter1.0.31\node_modules (no \ before version) and it fixed. That folder didn't reappear. That makes me wonder, why the unnecessary folder will affect this tool? I didn't try the latest CI build.

**Comment by madskristensen** [comment]
That's because the folder is now called `WebAnalyzer1.1.xxx` after I renamed the extension
