### ISSUE TITLE
System.Net.WebException: The remote server returned an error: (403) Forbidden.

### ISSUE THREAD

**Issue by bbodenmiller** [madskristensen/WebAnalyzer#3]
Getting the following error when the linter tries to process any of my .js files:

```
10/11/2015 2:58:20 AM: System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WebLinter.NodeServer.<CallServer>d__7.MoveNext() in C:\projects\webanalyzer\src\WebLinter\NodeServer.cs:line 28
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WebLinter.LinterBase.<RunProcess>d__29.MoveNext() in C:\projects\webanalyzer\src\WebLinter\Linting\Linters\LinterBase.cs:line 81
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WebLinter.LinterBase.<Lint>d__28.MoveNext() in C:\projects\webanalyzer\src\WebLinter\Linting\Linters\LinterBase.cs:line 59
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WebLinter.LinterBase.<Run>d__27.MoveNext() in C:\projects\webanalyzer\src\WebLinter\Linting\Linters\LinterBase.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WebLinter.LinterFactory.<Lint>d__4.MoveNext() in C:\projects\webanalyzer\src\WebLinter\Linting\LinterFactory.cs:line 72
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at WebLinterVsix.LinterService.<Lint>d__2.MoveNext() in C:\projects\webanalyzer\src\WebLinterVsix\LinterService.cs:line 61
```

**Comment by bbodenmiller** [comment]
Disconnected from my corporate VPN and it works fine. Reconnected to corporate VPN and it is broken again. What connection is it trying to make on every run that is being blocked?

**Comment by madskristensen** [comment]
Can you please try the latest CI build and see if the issue is fixed? http://vsixgallery.com/extension/36bf2130-106e-40f2-89ff-a2bdac6be879/

The connection is to a Node.js server that runs the linters

**Comment by bbodenmiller** [comment]
No error when running CI build however when connected to VPN no validation errors show in error list, when I discount they show in error list.

**Comment by madskristensen** [comment]
Ok, it seems like it is a proxy issue. I need to set the proxy settings correctly. Give me a few minutes and then a new CI build is ready

**Comment by madskristensen** [comment]
Build 1.2.26 is ready now. http://vsixgallery.com/extension/36bf2130-106e-40f2-89ff-a2bdac6be879/

Please try that. If it still doesn't work then I have another trick we should try.

**Comment by bbodenmiller** [comment]
Thanks for working on this. Works with no VPN but still no luck when connected to the VPN. Do you need any other debugging info?

**Comment by madskristensen** [comment]
Can you normally acces http://localhost without any issues?

**Comment by madskristensen** [comment]
I think I figured it out. I was using `http://locahost.` (notice the dot at the end) to trick the proxy settings. By removing the dot it should now correctly bypass the proxy when hitting localhost. Build 1.2.27 is ready in a few minutes for testing here http://vsixgallery.com/extension/36bf2130-106e-40f2-89ff-a2bdac6be879/

**Comment by bbodenmiller** [comment]
Looks like https://github.com/madskristensen/WebAnalyzer/commit/cf06d8ee8a00cc813ba2ba80972adaee86cb699e fixed it.

**Comment by madskristensen** [comment]
Awesome. Thanks for helping out testing :+1:
