### ISSUE TITLE
VS2015.2 crash

### ISSUE THREAD

**Issue by miksh7** [madskristensen/WebAnalyzer#30]
Steps:
1. Open TFS changeset details
2. Start comparing changes in the js files
3. VS crashes with

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at WebLinterVsix.SinkManager+<>c__DisplayClass6_0.<RemoveSnapshots>b__0(WebLinterVsix.TableEntriesSnapshot)
   at System.Linq.Enumerable.FirstOrDefault[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.Func`2<System.__Canon,Boolean>)
   at WebLinterVsix.SinkManager.RemoveSnapshots(System.Collections.Generic.IEnumerable`1<System.String>)
   at WebLinterVsix.TableDataSource.CleanErrors(System.Collections.Generic.IEnumerable`1<System.String>)
   at WebLinterVsix.FileListeners.SourceFileCreationListener+<>c__DisplayClass10_0.<TextviewClosed>b__0(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by rich-newman** [comment]
Thanks for the bug report.  I've had a look, but as you can imagine it's pretty hard to diagnose exactly from just the stack trace.

What I can see is [the line that's causing the problem](https://github.com/rich-newman/typescript-analyzer/blob/ea4b38fa05f33fe3c88bf4c92a63194fbc99f732/src/WebLinterVsix/ErrorList/SinkManager.cs#L52).  This is [code that I have inherited from Mads](https://github.com/madskristensen/WebAnalyzer/blob/da075ae1078827067fef8d61ea20ded640ce1990/src/WebLinterVsix/ErrorList/SinkManager.cs#L52) so it may well be the same issue you mention.  

I think the only way this line can throw that exception is if another thread alters the _snapshots collection at the exact same time this code is trying to execute FirstOrDefault.  However it's not clear how this could happen.  

In any case I'll put some better defense in for the next release.

Of course, it's also possible that something else caused the crash leaving the analyzer's thread execution in a mess and throwing exceptions.
